/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Clases.*;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ginop
 */
public class Panel_CC extends javax.swing.JPanel {

    /**
     * Creates new form Panel_CC
     */
    public Panel_CC() {
        initComponents();
        jTableCC.getTableHeader().setFont(new Font("Roboto",Font.BOLD,12));
        jTableCC.getTableHeader().setOpaque(false);
        jTableCC.getTableHeader().setBackground(new Color(102,0,204));
        jTableCC.getTableHeader().setForeground(new Color(102,0,204));
        jTableCC.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCC = new javax.swing.JTable();
        jtextfieldnombrezona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        aceptarlabel = new javax.swing.JLabel();
        vaciarlabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(18, 22, 24));
        setMaximumSize(new java.awt.Dimension(1090, 560));
        setMinimumSize(new java.awt.Dimension(1090, 560));
        setPreferredSize(new java.awt.Dimension(1090, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese la zona:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        jTableCC.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTableCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PATENTE", "MODELO", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableCC.setFocusable(false);
        jTableCC.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableCC.setMinimumSize(new java.awt.Dimension(90, 0));
        jTableCC.setSelectionBackground(new java.awt.Color(204, 0, 255));
        jScrollPane1.setViewportView(jTableCC);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 680, 340));

        jtextfieldnombrezona.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jtextfieldnombrezona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204), 2));
        jtextfieldnombrezona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldnombrezonaActionPerformed(evt);
            }
        });
        add(jtextfieldnombrezona, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultar Camiones Activos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        aceptarlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_checked_checkbox_50px_1.png"))); // NOI18N
        aceptarlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptarlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarlabelMouseClicked(evt);
            }
        });
        add(aceptarlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, 50));

        vaciarlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_waste_50px.png"))); // NOI18N
        vaciarlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vaciarlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaciarlabelMouseClicked(evt);
            }
        });
        add(vaciarlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfieldnombrezonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldnombrezonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldnombrezonaActionPerformed

    private void aceptarlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarlabelMouseClicked
    borrarFilaATabla();
    int tam_arraycam=0;
    String nzona;
    nzona=jtextfieldnombrezona.getText();
    if(!(nzona.equals(""))){
        if((PPv3.obtenerZona(nzona))!=null){
            Zona zaux=new Zona(PPv3.obtenerZona(nzona)); //se pasa por dir pero no copio el arraylist jeje       
            zaux.consultar_camiones();
            tam_arraycam=zaux.obtenerArrayListCamion().size(); 
            for(int i=0;i<tam_arraycam;i++){
            agregarFilaATabla(new Object[]{zaux.obtenerArrayListCamion().get(i).getPatente(),zaux.obtenerArrayListCamion().get(i).getModelo(),zaux.obtenerArrayListCamion().get(i).getEstado()});
             }
        }else{JOptionPane.showMessageDialog(this,"Zona invalida");}
    }else{JOptionPane.showMessageDialog(this,"Debe ingresar una zona");}
    }//GEN-LAST:event_aceptarlabelMouseClicked

    private void vaciarlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaciarlabelMouseClicked
       borrarFilaATabla();
       jtextfieldnombrezona.setText(null);
    }//GEN-LAST:event_vaciarlabelMouseClicked
    // Metodo que agrega un nuevo dato a la tabla principal: 
    public void agregarFilaATabla(Object[] datoFila)
    {
        DefaultTableModel modelo = (DefaultTableModel) jTableCC.getModel();
        modelo.addRow(datoFila);
    }

    public void borrarFilaATabla(){
    DefaultTableModel modelo = (DefaultTableModel)jTableCC.getModel();
    modelo.setRowCount(0);
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aceptarlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCC;
    private javax.swing.JTextField jtextfieldnombrezona;
    private javax.swing.JLabel vaciarlabel;
    // End of variables declaration//GEN-END:variables
}
