/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.time.LocalDateTime;

/**
 *
 * @author ginop
 */
public class Panel_Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Inicio
     */
    public Panel_Inicio() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        creators = new javax.swing.JLabel();

        setBackground(new java.awt.Color(18, 22, 24));
        setPreferredSize(new java.awt.Dimension(650, 440));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡Bienvenido! - ¡Benvenuti!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 60));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("consultar los camiones activos y los empleados de una zona particular.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 580, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sea bienvenido al sistema de gestion de residuos de la municipalidad de verona.  ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 660, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Aquí podrá agregar y eliminar empleados a la base de datos de la municipalidad, así como tambien  ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 820, 30));

        creators.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        creators.setForeground(new java.awt.Color(255, 255, 255));
        creators.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_code_file_40px.png"))); // NOI18N
        creators.setText("Arregui Daiana, García Franco & Paoletti Gino");
        add(creators, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, 40));
    }// </editor-fold>//GEN-END:initComponents
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creators;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
