/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import BD.Conexion;
import Clases.Empleado;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 */
public class PantallaEliminarEmp extends javax.swing.JFrame {

    /**
     * Creates new form PantallaEliminarEmp
     */
    public PantallaEliminarEmp() {
        initComponents();
        this.setTitle("Eliminar empleado");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLtitulo = new javax.swing.JLabel();
        jTFlegajobaja = new javax.swing.JTextField();
        jLlegajo = new javax.swing.JLabel();
        acept = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 36, 39));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLtitulo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLtitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_minus_60px.png"))); // NOI18N
        jPanel1.add(jLtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 60, 51));

        jTFlegajobaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFlegajobajaKeyTyped(evt);
            }
        });
        jPanel1.add(jTFlegajobaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, -1));

        jLlegajo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLlegajo.setForeground(new java.awt.Color(255, 255, 255));
        jLlegajo.setText("Legajo:");
        jPanel1.add(jLlegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        acept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_checked_checkbox_50px_1.png"))); // NOI18N
        acept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptMouseClicked(evt);
            }
        });
        jPanel1.add(acept, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Eliminar(){
    
        if(jTFlegajobaja.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Complete el campo.");  
         }else{
        Conexion con  = new Conexion();//creo la conexion
      
        try{
             Connection connect  = con.Conectar();//abro la conexion
             java.sql.Statement st = connect.createStatement(); //objeto para realizar la consulta
             String sql = "SELECT * FROM empleados WHERE elegajo = '"+jTFlegajobaja.getText()+"';";
             ResultSet rs = st.executeQuery(sql);
             if(rs.next()){ //SI SE ENCONTRARON LOS VALORES
             Empleado emp = new Empleado(rs.getString("enombre"),rs.getString("edni"),rs.getString("elegajo"),rs.getString("etel"),rs.getString("edireccion"),rs.getString("ecargo"));
                int opcion = JOptionPane.showOptionDialog(null, "DNI: "+ emp.getDni() + "\n" + "Nombre: "+ emp.getNombre() + "\n" + "Legajo: " + emp.getLegajo() + "\n" + "Teléfono: " + emp.getTelefono() + "\n" + "Dirección: " + emp.getDireccion() + "\n" + "Cargo: " + emp.getCargo() + "\n" + "¿Está seguro que desea dar de baja?", //contenido de la ventana
                         " " , //titulo de la ventana
                         JOptionPane.OK_CANCEL_OPTION, //para 2 botones 
                         JOptionPane.QUESTION_MESSAGE, //tipo de ícono
                         null,    // null para icono por defecto.
                         new Object[] { "Aceptar", "Cancelar"},//objeto para las opciones
                         "Aceptar"); //selección predeterminada
        if(opcion==0){
            sql = "DELETE FROM empleados WHERE elegajo = '"+emp.getLegajo()+"';";
            st.executeUpdate(sql); 
            JOptionPane.showMessageDialog(null,"Baja Exitosa.");   
        }
        else  JOptionPane.showMessageDialog(null,"Baja cancelada.");
           
            }else{ 
                JOptionPane.showMessageDialog(null,"Empleado no registrado.");
            }        
         st.close();
         connect = con.Cerrar();//Cierro la conexion
         jTFlegajobaja.setText("");
        this.setVisible(false);
        }catch(Exception e)
        {
        JOptionPane.showMessageDialog(this, "Baja Fallida.");
        jTFlegajobaja.setText("");
        this.setVisible(false);
        }
                }
    }
    
    
    private void jTFlegajobajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFlegajobajaKeyTyped
        // TODO add your handling code here:
         if(jTFlegajobaja.getText().length() >=6 ){ evt.consume(); }
    }//GEN-LAST:event_jTFlegajobajaKeyTyped

    private void aceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptMouseClicked
        Eliminar();
    }//GEN-LAST:event_aceptMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acept;
    private javax.swing.JLabel jLlegajo;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFlegajobaja;
    // End of variables declaration//GEN-END:variables
}
